### ISSUE TITLE
签名好像更新了

### ISSUE THREAD

**Issue by fei-ju** [Bpazy/wl520#8]
抓了个包看了下好像改成md5了 旧的签名方式没法用了

**Comment by Bpazy** [comment]
我测试了一下并没有出现你描述的问题，请提供下详细的错误日志或抓包的结果（上传结果前请重新登录微爱以重置签名），另外你是Android还是iOS
![snipaste_2018-12-23_14-52-11](https://user-images.githubusercontent.com/9838749/50381495-5c64a580-06c3-11e9-996c-316d0bc7ed2a.png)

**Comment by fei-ju** [comment]
不好意思  是农场部分 我是用的安卓

![image](https://user-images.githubusercontent.com/26491646/50384057-f1987780-068c-11e9-887a-c08caaf2fe3f.png)

![image](https://user-images.githubusercontent.com/26491646/50384064-1987db00-068d-11e9-9956-3c6c63a4f90e.png)

**Comment by Bpazy** [comment]
#### Duplicate of #9 
关闭这个issue，更多相关的回复请转移到 #9
